# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-14 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170914_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='twit',
        ),
        migrations.RemoveField(
            model_name='twit',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Twit',
        ),
    ]
